/**
 * 从 packages/shared/src/types/ipc.ts 生成 apps/desktop/src/preload/ipc-constants.cjs。
 *
 * 背景：preload 必须是 CommonJS（Electron 沙箱），且刻意不依赖 workspace 包；
 * 过去 IPC 常量在 shared 与 preload 双写，靠 verify-ipc-sync.cjs 事后比对（漂移是常态风险）。
 * 现在改为「生成」：ipc.ts 是唯一事实源，本脚本产出 preload 侧常量文件，
 * verify-ipc-sync.cjs 只检查产物是否过期（--check 模式）。
 *
 * 用法：
 *   node scripts/generate-preload.cjs          # 重新生成
 *   node scripts/generate-preload.cjs --check   # 只检查是否过期（lint 阶段用）
 */
const fs = require('node:fs');
const path = require('node:path');

const sharedPath = path.resolve(__dirname, '../packages/shared/src/types/ipc.ts');
const outPath = path.resolve(__dirname, '../apps/desktop/src/preload/ipc-constants.cjs');

function extractConstants(text) {
  const obj = {};
  const regex = /(\w+)\s*:\s*'([^']+)'/g;
  let m;
  while ((m = regex.exec(text)) !== null) {
    // 跳过类型/注释中的误匹配：只接受 IPC 对象体内的 key（所有 key 都是大写通道名）
    if (/^[A-Z][A-Z0-9_]*$/.test(m[1])) {
      obj[m[1]] = m[2];
    }
  }
  return obj;
}

function render(shared) {
  const keys = Object.keys(shared);
  const body = keys.map((k) => `  ${k}: '${shared[k]}',`).join('\n');
  return [
    '// AUTO-GENERATED by scripts/generate-preload.cjs — DO NOT EDIT.',
    '// 事实源: packages/shared/src/types/ipc.ts。',
    '// 改动 IPC 通道后运行 `pnpm generate:ipc`（或 node scripts/generate-preload.cjs）重新生成；',
    '// `pnpm lint` 会通过 verify-ipc-sync.cjs 检查本产物未过期。',
    'const IPC = {',
    body,
    '};',
    '',
    'module.exports = { IPC };',
    '',
  ].join('\n');
}

function main() {
  const check = process.argv.includes('--check');
  const sharedText = fs.readFileSync(sharedPath, 'utf8');
  const shared = extractConstants(sharedText);
  const rendered = render(shared);

  if (check) {
    if (!fs.existsSync(outPath)) {
      console.error('[generate-preload] STALE: ' + path.relative(process.cwd(), outPath) + ' missing — run `pnpm generate:ipc`.');
      process.exit(1);
    }
    // 行尾归一化：脚本生成 LF，磁盘文件可能因 git autocrlf 是 CRLF，全等比较会误报 STALE。
    const current = fs.readFileSync(outPath, 'utf8').replace(/\r\n/g, '\n');
    if (current !== rendered) {
      console.error('[generate-preload] STALE: preload IPC constants out of date — run `pnpm generate:ipc`.');
      process.exit(1);
    }
    console.log(`[generate-preload] up to date (${Object.keys(shared).length} channels).`);
    return;
  }

  // 幂等写入：内容相同跳过。本文件由 dev-watch 的 regenPreload 每次重启都调用，
  // 无条件重写会写入被监视的 src/preload/，自我触发重启循环（实测 80+ 次/60s）。
  const current = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === rendered) {
    console.log(`[generate-preload] up to date (${Object.keys(shared).length} channels).`);
    return;
  }
  fs.writeFileSync(outPath, rendered, 'utf8');
  console.log(`[generate-preload] OK: ${path.relative(process.cwd(), outPath)} (${Object.keys(shared).length} channels).`);
}

main();
